version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
      - ./mongo-seed:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass  # 這裡修改為你想要的密碼

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-seed:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  ### admin Spring Boot 專案
  admin-service:
    build: ./backend/admin
    container_name: admin-service
    environment:
      DATASOURCE_URL: postgres
      DATASOURCE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      MONGODB_URI: mongodb
      MONGODB_PORT: 27017
    ports:
      - "9100:9100"
    depends_on:
      - rabbitmq
      - redis
      - mongodb
      - postgres
    networks:
      - default

### 🔴 加入 bot Spring Boot 專案
  bot-service:
    build: ./backend/bot
    container_name: bot-service
    environment:
      DATASOURCE_URL: postgres
      DATASOURCE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      MONGODB_URI: mongodb
      MONGODB_PORT: 27017
      RASA_IP: rasa-bot
      RASA_PORT: 5005
      ADMIN_IP: admin-service
      ADMIN_PORT: 9100
    ports:
      - "9200:9200"
    depends_on:
      - rasa-bot
      - admin-service
    networks:
      - default

  ### 🔴 加入 portal Spring Boot 專案
  portal-service:
    build: ./backend/portal
    container_name: portal-service
    environment:
      DATASOURCE_URL: postgres
      DATASOURCE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      MONGODB_URI: mongodb
      MONGODB_PORT: 27017
    ports:
      - "8080:8080"
    depends_on:
      - bot-service
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/customer:/usr/share/nginx/html
    depends_on:
      - portal-service
    networks:
      - default

volumes:
  mongo_data:
  postgres_data:
