version: "3.1"

language: zh

pipeline:
- name: JiebaTokenizer
    # dictionary_path: "path/to/dict.txt"  # 如果有自訂詞庫，可填路徑
- name: RegexFeaturizer
- name: RegexEntityExtractor
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  token_pattern: None
- name: CountVectorsFeaturizer
  analyzer: char_wb
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true    # 讓意圖與實體互相約束，提高準確度
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
assistant_id: 20250602-003438-green-martin
